# docker-stack-rm
# Autogenerated from man page /usr/share/man/man1/docker-stack-rm.1.gz
complete -c docker-stack-rm -s h -l help --description '    help for rm OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c docker-stack-rm -l kubeconfig --description '    Kubernetes config file.'
complete -c docker-stack-rm -l namespace --description '    Kubernetes namespace to use SEE ALSO.'

