# docker-stack-ls
# Autogenerated from man page /usr/share/man/man1/docker-stack-ls.1.gz
complete -c docker-stack-ls -l format --description '    Pretty-print stacks using a Go template.'
complete -c docker-stack-ls -s h -l help --description '    help for ls OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c docker-stack-ls -l kubeconfig --description '    Kubernetes config file.'
complete -c docker-stack-ls -l namespace --description '    Kubernetes namespace to use SEE ALSO.'

