# gpg-wks-server
# Autogenerated from man page /usr/share/man/man1/gpg-wks-server.1.gz
complete -c gpg-wks-server -l from --description 'Use mailaddr as the default sender address.'
complete -c gpg-wks-server -l header --description 'Add the mail header "name: value" to all outgoing mails.'
complete -c gpg-wks-server -l send --description 'Directly send created mails using the sendmail command.'
complete -c gpg-wks-server -l output --description 'TQ   -o Write the created mail also to file.'
complete -c gpg-wks-server -l verbose --description 'Enable extra informational output.'
complete -c gpg-wks-server -l quiet --description 'Disable almost all informational output.'
complete -c gpg-wks-server -l version --description 'Print version of the program and exit.'
complete -c gpg-wks-server -l revoke-key --description 'OPTIONS.'
complete -c gpg-wks-server -s o --description 'Write the created mail also to file.  Note that the value.'
complete -c gpg-wks-server -l help --description 'Display a brief help page and exit.  EXAMPLES.'

