# makemap
# Autogenerated from man page /usr/share/man/man8/makemap.8.gz
complete -c makemap -s d --description 'Specify the format of the database.  Available formats are hash and btree.'
complete -c makemap -s o --description 'Write the generated database to dbfile.'
complete -c makemap -s t --description 'Specify the format of the resulting map file.'
complete -c makemap -s U --description 'Instead of generating a database map from text input, dump the contents of a …'

