# mysql_zap
# Autogenerated from man page /usr/share/man/man1/mysql_zap.1.gz
complete -c mysql_zap -o signal --description 'option is given, it specifies the name or number of the signal to send to eac…'
complete -c mysql_zap -l help --description '.'
complete -c mysql_zap -s '?' --description '.'
complete -c mysql_zap -s I --description '.'
complete -c mysql_zap -s f --description '.'
complete -c mysql_zap -s t --description '.'

