# newaliases
# Autogenerated from man page /usr/share/man/man8/newaliases.8.gz
complete -c newaliases -s f --description 'Use file as the configuration file, instead of the default /etc/smtpd/smtpd.'

