# npm-install
# Autogenerated from man page /usr/share/man/man1/npm-install.1
complete -c npm-install -s P -l save-prod --description '               default unless `-D` or `-O` are present.  o 2.'
complete -c npm-install -s D -l save-dev --description 'o 2.'
complete -c npm-install -s O -l save-optional --description 'o 2.'
complete -c npm-install -l no-save --description 'When using any of the above options to save dependencies to your package.'
complete -c npm-install -s E -l save-exact --description 'exact version rather than using npm\'s default semver range operator.  o 2.'
complete -c npm-install -s B -l save-bundle --description 'Further, if you have an npm-shrinkwrap. json or package-lock.'

