# npm-dist-tag
# Autogenerated from man page /usr/share/man/man1/npm-dist-tag.1
complete -c npm-dist-tag -l tag --description 'have two-factor authentication on auth-and-writes then you\'ll need to include…'

