# npm-uninstall
# Autogenerated from man page /usr/share/man/man1/npm-uninstall.1
complete -c npm-uninstall -s S -l save --description 'o 2.'
complete -c npm-uninstall -s D -l save-dev --description 'o 2.'
complete -c npm-uninstall -s O -l save-optional --description 'o 2.'
complete -c npm-uninstall -l no-save --description 'Further, if you have an npm-shrinkwrap. json then it will be updated as well.'

