# nss-config
# Autogenerated from man page /usr/share/man/man1/nss-config.1.gz
complete -c nss-config -l prefix --description 'Returns the top level system directory under which the nss libraries are inst…'
complete -c nss-config -l exec-prefix --description 'returns the top level system directory under which any nss binaries would be …'
complete -c nss-config -l includedir --description 'returns the path to the directory were the nss libraries are installed.'
complete -c nss-config -l version --description 'returns the upstream version of nss in the form major_version-minor_version-p…'
complete -c nss-config -l libs --description 'returns the compiler linking flags.'
complete -c nss-config -l cflags --description 'returns the compiler include flags.'
complete -c nss-config -l libdir --description 'returns the path to the directory were the nss libraries are installed.'

