# pg_basebackup
# Autogenerated from man page /usr/share/man/man1/pg_basebackup.1.gz
complete -c pg_basebackup -s D --description 'Directory to write the output to.'
complete -c pg_basebackup -s r --description 'The maximum transfer rate of data transferred from the server.'
complete -c pg_basebackup -o 'R
.br
--write-recovery-conf' --description 'Write a minimal recovery.'
complete -c pg_basebackup -s S --description 'This option can only be used together with -X stream.'
complete -c pg_basebackup -s T --description 'Relocate the tablespace in directory olddir to newdir during the backup.'
complete -c pg_basebackup -l xlogdir --description 'Specifies the location for the transaction log directory.'
complete -c pg_basebackup -o 'x
.br
--xlog' --description 'Using this option is equivalent of using -X with method fetch.'
complete -c pg_basebackup -o 'z
.br
--gzip' --description 'Enables gzip compression of tar file output, with the default compression lev…'
complete -c pg_basebackup -s Z --description 'Enables gzip compression of tar file output, and specifies the compression le…'
complete -c pg_basebackup -s c --description 'Sets checkpoint mode to fast (immediate) or spread (default) (see Section 25.'
complete -c pg_basebackup -s l --description 'Sets the label for the backup.'
complete -c pg_basebackup -o 'P
.br
--progress' --description 'Enables progress reporting.'
complete -c pg_basebackup -o 'v
.br
--verbose' --description 'Enables verbose mode.'
complete -c pg_basebackup -s d --description 'Specifies parameters used to connect to the server, as a connection string.'
complete -c pg_basebackup -s h --description 'Specifies the host name of the machine on which the server is running.'
complete -c pg_basebackup -s p --description 'Specifies the TCP port or local Unix domain socket file extension on which th…'
complete -c pg_basebackup -s s --description 'Specifies the number of seconds between status packets sent back to the serve…'
complete -c pg_basebackup -s U --description 'User name to connect as.'
complete -c pg_basebackup -o 'w
.br
--no-password' --description 'Never issue a password prompt.'
complete -c pg_basebackup -o 'W
.br
--password' --description 'Force pg_basebackup to prompt for a password before connecting to a database.'
complete -c pg_basebackup -o 'V
.br
--version' --description 'Print the pg_basebackup version and exit.'
complete -c pg_basebackup -o '?
.br
--help' --description 'Show help about pg_basebackup command line arguments, and exit.'
complete -c pg_basebackup -s x --description 'option.  oc o 2. 3.'
complete -c pg_basebackup -l pgdata --description '.'
complete -c pg_basebackup -s F --description '.'
complete -c pg_basebackup -l format --description '.'
complete -c pg_basebackup -l max-rate --description '.'
complete -c pg_basebackup -s R --description '.'
complete -c pg_basebackup -l write-recovery-conf --description '.'
complete -c pg_basebackup -l slot --description '.'
complete -c pg_basebackup -s X --description 'recovery. conf.'
complete -c pg_basebackup -l tablespace-mapping --description '.'
complete -c pg_basebackup -l xlog --description '.'
complete -c pg_basebackup -l xlog-method --description '.'
complete -c pg_basebackup -s z --description '.'
complete -c pg_basebackup -l gzip --description '.'
complete -c pg_basebackup -l compress --description '.'
complete -c pg_basebackup -l checkpoint --description '.'
complete -c pg_basebackup -l label --description '.'
complete -c pg_basebackup -s P --description '.'
complete -c pg_basebackup -l progress --description '.'
complete -c pg_basebackup -s v --description '.'
complete -c pg_basebackup -l verbose --description '.'
complete -c pg_basebackup -l dbname --description '.'
complete -c pg_basebackup -l host --description '.'
complete -c pg_basebackup -l port --description '.'
complete -c pg_basebackup -l status-interval --description '.'
complete -c pg_basebackup -l username --description '.'
complete -c pg_basebackup -s w --description '.'
complete -c pg_basebackup -l no-password --description '.'
complete -c pg_basebackup -s W --description '.'
complete -c pg_basebackup -l password --description '.'
complete -c pg_basebackup -s V --description '.'
complete -c pg_basebackup -l version --description '.'
complete -c pg_basebackup -s '?' --description '.'
complete -c pg_basebackup -l help --description '.'

