# pg_resetxlog
# Autogenerated from man page /usr/share/man/man1/pg_resetxlog.1.gz
complete -c pg_resetxlog -s f --description 'Force pg_resetxlog to proceed even if it cannot determine valid data for pg_c…'
complete -c pg_resetxlog -s n --description 'The -n (no operation) option instructs pg_resetxlog to print the values recon…'
complete -c pg_resetxlog -o 'V
.br
--version' --description 'Display version information, then exit.'
complete -c pg_resetxlog -o '?
.br
--help' --description 'Show help, then exit.'
complete -c pg_resetxlog -s c --description 'Manually set the oldest and newest transaction IDs for which the commit time …'
complete -c pg_resetxlog -s e --description 'Manually set the next transaction ID\\*(Aqs epoch.'
complete -c pg_resetxlog -s l --description 'Manually set the WAL starting address.'
complete -c pg_resetxlog -s m --description 'Manually set the next and oldest multitransaction ID.'
complete -c pg_resetxlog -s o --description 'Manually set the next OID.'
complete -c pg_resetxlog -s O --description 'Manually set the next multitransaction offset.'
complete -c pg_resetxlog -s x --description 'Manually set the next transaction ID.'
complete -c pg_resetxlog -s V --description '.'
complete -c pg_resetxlog -l version --description '.'
complete -c pg_resetxlog -s '?' --description '.'
complete -c pg_resetxlog -l help --description '.'

