# sendmail
# Autogenerated from man page /usr/share/man/man8/sendmail.8.gz
complete -c sendmail -s F --description 'Set the sender\'s full name.'
complete -c sendmail -s f --description 'Set the sender\'s address.'
complete -c sendmail -s t --description 'Read the message\'s To:, Cc:, and Bcc: fields for recipients.'
complete -c sendmail -s v --description 'Enable verbose output.  El Pp To maintain compatibility with Sendmail, Inc.'

