# smtpd
# Autogenerated from man page /usr/share/man/man8/smtpd.8.gz
complete -c smtpd -s D --description 'Define macro to be set to value on the command line.'
complete -c smtpd -s d --description 'Do not daemonize.'
complete -c smtpd -s F --description 'Do not daemonize.'
complete -c smtpd -s f --description 'Specify an alternative configuration file.'
complete -c smtpd -s h --description 'Display version and usage.'
complete -c smtpd -s n --description 'Configtest mode.  Only check the configuration file for validity.'
complete -c smtpd -s P --description 'Pause a specific subsystem at startup.'
complete -c smtpd -s T --description 'Enables real-time tracing at startup.'
complete -c smtpd -s v --description 'Produce more verbose output.  El FILES -tag -width "/etc/smtpd/smtpd.'

