# vsftpd
# Autogenerated from man page /usr/share/man/man8/vsftpd.8.gz
complete -c vsftpd -s v --description 'Print the version information and exit, even if other options are encountered.'
complete -c vsftpd -o ooption --description 'Set a single option, value pair as per the format in the config file.'

