# zipcmp
# Autogenerated from man page /usr/share/man/man1/zipcmp.1.gz
complete -c zipcmp -s h --description 'Display a short help message and exit.'
complete -c zipcmp -s i --description 'Compare names ignoring case distinctions.'
complete -c zipcmp -s p --description 'Enable paranoid checks.  Compares extra fields and other meta data.'
complete -c zipcmp -s q --description 'Quiet mode.  Compare.'
complete -c zipcmp -s v --description '.'
complete -c zipcmp -s t --description 'Test zip files by comparing the contents to their checksums.'
complete -c zipcmp -s V --description 'Display version information and exit.'

