# ziptool
# Autogenerated from man page /usr/share/man/man1/ziptool.1.gz
complete -c ziptool -s c --description 'Check zip archive consistency when opening it.'
complete -c ziptool -s e --description 'Error if archive already exists (only useful with.'
complete -c ziptool -s n --description '.'
complete -c ziptool -s g --description 'Guess file name encoding (for stat command).'
complete -c ziptool -s H --description 'Write files with holes compactly.'
complete -c ziptool -s h --description 'Display help.'
complete -c ziptool -s l --description 'Only read length bytes of archive.  See also.'
complete -c ziptool -s o --description '.'
complete -c ziptool -s m --description 'Read archive into memory, and modify there; write out at end.'
complete -c ziptool -s r --description 'Print raw file name encoding without translation (for stat command).'
complete -c ziptool -s s --description 'Follow file name convention strictly (for stat command).'
complete -c ziptool -s t --description 'Disregard current file contents, if any.'

